"""Builds the *evidence sidecar* -- a standalone document rendered beside
a draft, listing each cited source and the verbatim spans its dossier
recorded as quotable, grouped by the draft section that leans on them.

`content/rendered/<topic>/survey.evidence.pdf` sits next to
`content/rendered/<topic>/survey.pdf`. Planned in
plans/a4-evidence-appendix.md, which is the authoritative design;
docs/FEATURE-ROADMAP.md's A4 is the roadmap entry.

**Why a sidecar and not a section inside the draft.** The roadmap and
#313 both describe an `Evidence` appendix *inside* the document. It is
not one, and the reason is not stated in either: `content/dossiers/` is
gitignored precisely because `evidence.md` quotes copyrighted sources,
but `content/drafts/digital-twins-for-software-engineers/` and
`content/rendered/digital-twins-for-software-engineers/` are tracked. An
appendix inside the draft would commit quoted spans from copyrighted PDFs
to a public repository. A sidecar can be excluded by pattern; a section
inside a tracked draft cannot.

**The one field this prints, and the documented rule it narrows.** Only
`quote:`. docs/DRAFT-ITERATION.md says a *skill* meeting a legacy
`support:`-only block "reads it as `quote:` -- the conservative reading",
and `draft-reviser`/`corpus-reviser` both state it as their own
behaviour. That is right for a drafter deciding whether it *may quote
from* a block. It is wrong here, and this module deliberately does not
inherit it: a legacy `support:` holds a raw 600-character retrieval
window (`EVIDENCE_CHARS` in chitragupta/retrieval.py), and printing one
as a "quoted, attributed span" in a rendered PDF is exactly the
publication of source wording this feature exists to prevent. `claim:` is
excluded for the opposite reason -- it is the drafter's own words, so
quoting it back would attribute this project's prose to the source.

**Two properties held as shapes rather than as checks**, because #313
rules out promoting a new check into a gate:

1. A sidecar can never introduce a citekey. Its universe is
   `references.used_citekeys()` over the draft, so a key the dossier
   holds but the draft does not cite is dropped -- `references.py`'s own
   rule, inherited rather than restated.
2. A sidecar contributes zero citations. Every citekey it prints sits in
   a code span, which `citation_gate._blank_code` blanks before
   extraction. Running the gate over a sidecar reports `0 citations ...
   OK`, and the sidecar cannot perturb the body's first-appearance
   numbering, which `references.numbered_markdown` and pandoc's citeproc
   both depend on.

Nothing to say means no file: no dossier, or no `quote:` anywhere in it,
and `build()` returns None. That is how a genre declines -- not a switch,
but the absence of deliberate quotes. `tutorial-writer` cites only in
"Where to go next" and captures no `quote:`, so it emits nothing without
anyone configuring anything.

Usage:
    python -m chitragupta.draft evidence <file.md> [--format md|tex|pdf]
"""

import argparse
import subprocess
import sys
from pathlib import Path

from chitragupta import config, ledger, references
from chitragupta.dossier import citekeys_by_section, dossier_dir
from chitragupta.dossier._citekeys import evidence_blocks
from chitragupta.dossier._evidence_check import fields

# Where a key the draft cites but `sections.md` files nowhere is
# collected. Named rather than dropped, and named rather than filed under
# a section that does not contain it -- the same answer
# `dossier sections --citekeys` already gives for an unfiled key.
UNASSIGNED = "Unassigned"

# The suffix that turns a draft's stem into its sidecar's. Referenced by
# chitragupta/dossier/_archive.py, which has to strip it to match a
# sidecar against the draft it belongs to, and by .gitignore, which
# excludes the pattern so a quoted span never reaches a commit. Changing
# it here without changing both is what tests/test_evidence_appendix.py's
# gitignore test exists to catch.
SUFFIX = "evidence"

_PREAMBLE = (
    "Generated by `python -m chitragupta.draft evidence` from this draft's own\n"
    "dossier. Every quoted span below is verbatim from the source named above\n"
    "it; nothing else in the draft is.\n"
)


def quoted_spans(draft_text: str, dossier: Path) -> dict[str, str]:
    """citekey -> its `quote:`, for keys the draft cites and the dossier
    quotes, in the draft's own first-appearance order.

    A block carrying only `relevance:`/`claim:`, or only a legacy
    `support:`, contributes nothing -- see this module's docstring for
    why `support:` is not read here even though a skill reads it as a
    quote.
    """
    blocks = evidence_blocks(dossier)
    found: dict[str, str] = {}
    for citekey in references.used_citekeys(draft_text):
        quote = fields(blocks[citekey]).get("quote") if citekey in blocks else None
        if quote:
            found[citekey] = quote
    return found


def grouped(spans: dict[str, str], dossier: Path) -> list[tuple[str, list[str]]]:
    """(section, its quoted citekeys) in `sections.md`'s own row order,
    with anything unfiled last under `UNASSIGNED`.

    A section whose citekeys all lack a quote is omitted entirely, so no
    heading is left standing above nothing. Row order rather than the
    draft's citation order because it is the order the run itself chose,
    and it is what `citekeys_by_section` already preserves.
    """
    by_section = citekeys_by_section(dossier)
    groups = [
        (title, [k for k in citekeys if k in spans])
        for title, citekeys in by_section.items()
    ]
    groups = [(title, keys) for title, keys in groups if keys]

    filed = {k for citekeys in by_section.values() for k in citekeys}
    unfiled = [k for k in spans if k not in filed]
    if unfiled:
        groups.append((UNASSIGNED, unfiled))
    return groups


def _blockquote(quote: str) -> str:
    """One `quote:` value as a Markdown blockquote, in quotation marks.

    A value that already carries its own surrounding quotation marks is
    not double-quoted: a human writing `quote: "..."` by hand and a skill
    writing it bare should produce the same rendered span.
    """
    text = quote.strip()
    if len(text) >= 2 and text.startswith('"') and text.endswith('"'):
        text = text[1:-1].strip()
    lines = f'"{text}"'.splitlines()
    return "\n".join(f"> {line}" for line in lines)


def build(draft_text: str, dossier: Path, con) -> str | None:
    """The sidecar's Markdown for `draft_text`, or None if there is none.

    None -- rather than an empty document -- whenever the draft cites
    nothing, the dossier does not exist, or no cited block carries a
    `quote:`. A caller writes a file only when this returns a string.

    A cited citekey with no ledger row raises `KeyError` through
    `references.entries`, which is AGENTS.md's citekey invariant and the
    same contract `references.build_section` holds: a source this cannot
    name is never printed as an unattributed quotation.
    """
    spans = quoted_spans(draft_text, dossier)
    if not spans:
        return None

    attributions = references.entries(list(spans), con)
    out = [f"# {SUFFIX.capitalize()}", "", _PREAMBLE]
    for title, citekeys in grouped(spans, dossier):
        out.append(f"## {title}")
        out.append("")
        for citekey in citekeys:
            # The citekey in a code span, exactly as references.py labels
            # a bibliography entry: it is what ties a stanza back to the
            # draft's own `[@citekey]`, and a code span is invisible to
            # citation_gate, so printing it here can never read as a
            # citation.
            out.append(f"### {attributions[citekey]} `{citekey}`")
            out.append("")
            out.append(_blockquote(spans[citekey]))
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def sidecar_path(draft: Path, out_dir: Path, output_format: str = "md") -> Path:
    """Where `draft`'s sidecar lands: `<stem>.evidence.<format>` in
    `out_dir`.

    One place computes this, because three things have to agree on it --
    the writer, `_archive.py`'s export matching, and `.gitignore`.
    """
    return out_dir / f"{draft.stem}.{SUFFIX}.{output_format}"


def write(draft: Path, out_dir: Path, draft_text: str | None = None) -> Path | None:
    """Writes `draft`'s Markdown sidecar into `out_dir`, or None if the
    draft has no quoted evidence to show.

    `draft_text` overrides what is read from disk, for a caller that has
    already read the draft once and must not risk the two disagreeing --
    the same override `references.write_numbered` takes, for the same
    reason.
    """
    if draft_text is None:
        draft_text = draft.read_text(encoding="utf-8")
    with ledger.connection() as con:
        text = build(draft_text, dossier_dir(draft), con)
    if text is None:
        return None

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = sidecar_path(draft, out_dir)
    out_path.write_text(text, encoding="utf-8")
    return out_path


def emit(draft: Path, output_format: str = "md", out_dir: Path | None = None) -> Path | None:
    """The sidecar for `draft` in `output_format`, or None if there is
    nothing to emit.

    Markdown is written directly; any other format is the Markdown
    handed back to `render_output.render()`. That is safe precisely
    because a sidecar carries no citations: citeproc has nothing to
    resolve, so no bibliography machinery -- and no biblatex, which this
    project does not require -- is involved in rendering one. It is also
    why a `thesis-chapter-writer` fragment can have a sidecar at all: the
    sidecar is a standalone document with its own preamble, never
    something a thesis `\\input`s.
    """
    # Deferred, and it has to be: render_output imports references and
    # config at module scope and is reached from chitragupta/draft.py's
    # dispatch, so importing it here at module scope would make the two
    # packages import each other on the way up. chitragupta/render_output/
    # _cli.py defers its own `render` import for the same reason.
    from chitragupta.render_output import render
    from chitragupta.render_output._paths import _output_dir

    draft = config.require_inside_content(draft)
    target = Path(out_dir) if out_dir is not None else _output_dir(draft)
    markdown = write(draft, target)
    if markdown is None or output_format == "md":
        return markdown
    return render(str(markdown), output_format, output_dir=str(target))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m chitragupta.draft evidence",
        description="Render the evidence sidecar beside a draft: each cited "
                    "source and the verbatim spans its dossier marked quotable.",
    )
    parser.add_argument("input", help="Path to the draft file (Markdown or LaTeX)")
    parser.add_argument("--format", dest="output_format", default="md",
                        help="Output format (default: md)")
    parser.add_argument(
        "--output-dir", default=None,
        help="Write the sidecar here instead of content/rendered/<mirrored path>. "
             "Confined to content/ like every other path this writes",
    )
    args = parser.parse_args(argv)
    # Imported here rather than at module scope for the same reason
    # `emit` defers `render`: chitragupta/render_output/ imports this
    # package's siblings and is reached from the same dispatch.
    from chitragupta.render_output._errors import MissingBinary

    try:
        out_path = emit(Path(args.input), args.output_format, args.output_dir)
    except (KeyError, config.OutsideContentDir) as exc:
        # Both are "this sidecar can't be built, and here is why" rather
        # than a bug: a citekey the ledger doesn't hold, or a path outside
        # content/. Reported on stderr like every other refusal in the
        # drafting layer instead of as a traceback.
        print(f"[error] {exc.args[0] if exc.args else exc}", file=sys.stderr)
        return 1
    except MissingBinary as exc:
        print(f"[missing-binary] {exc}", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as exc:
        # A non-`md` sidecar goes through pandoc, so it can fail the same
        # ways a render can. Caught for the same reason
        # chitragupta/render_output/_cli.py catches it: every genre skill
        # is documented to warn on `[error]`/`[missing-binary]` and carry
        # on presenting the draft, and a traceback is not something that
        # instruction can act on. The Markdown sidecar has already been
        # written at this point and is still on disk, which is the useful
        # half of the output.
        print(f"[error] pandoc failed: {exc.stderr or exc}", file=sys.stderr)
        return 1

    if out_path is None:
        # Exit 0: a draft with no deliberate quotes has nothing to show,
        # which is the expected answer for `tutorial-writer` and for any
        # dossier still carrying only legacy `support:` blocks. A refusal
        # here would train a genre skill to work around a non-problem.
        print(f"{args.input}: no quoted evidence recorded -- no sidecar written")
        return 0
    print(str(out_path))
    return 0
