"""Per-citekey TL;DR: a one-paragraph, human-authored summary, so
skimming a large corpus does not mean opening every PDF.

docs/FEATURE-ROADMAP.md's E1 named the placement as the whole design
decision. The summary is LLM output, so it cannot live in the corpus
layer -- SOUL.md's "no LLM and no judgment calls" -- and it is not
generated by anything in this module either: `write` only persists text
someone else composed (a person, or a skill in the current Claude Code
session) and never calls out to an LLM itself. It belongs to the
drafting layer, as an eleventh `chitragupta/draft.py` verb, in its own
sidecar under `content/tldr/` -- not `content/dossiers/`, because a
summary belongs to a citekey, not to any one draft's working state.
`python -m chitragupta.corpus ledger` is not touched by this at all.

**The fingerprint is a content hash of the parsed text, not a stat of
the PDF.** Mirrors chitragupta/enrich/embed_index.py's `hash_text` /
unchanged-text skip, deliberately not
chitragupta/enrich/docling_parse.py's `(size, mtime_ns)` fingerprint of
the *input* PDF: what must go stale is the text a summary was written
against, and a backend switch or a `--reparse` can change that text
without the PDF on disk moving at all, which a PDF-stat fingerprint
can't see. A re-parse that happens to produce byte-identical text
therefore correctly leaves a summary fresh -- this is a fingerprint of
`content/parsed/<citekey>.txt`'s *content*, not of when it was written.

**Staleness is binary and always re-derived on read, never stored.**
`read()` recomputes the current fingerprint every time and compares it
to what was stored at `write` time; it never trusts a flag written
earlier, which is what makes "re-fingerprint on read" (this module) and
"cache the verdict at write time" (the bug this module exists to avoid)
different code. There is no third state: a fingerprint that can no
longer be computed at all -- the citekey left the ledger, or its parsed
text is gone -- counts as stale too, since a summary that cannot be
verified is not reported as trustworthy.

Usage:
    echo "<summary text>" | python -m chitragupta.draft tldr write <citekey>
    python -m chitragupta.draft tldr show <citekey> [--json]
"""

import argparse
import hashlib
import json
import sys
from pathlib import Path

from chitragupta import config, ledger


class TldrError(Exception):
    """A citekey the ledger doesn't hold, one with no parsed text yet, or
    an empty summary."""


def sidecar_path(citekey: str) -> Path:
    """Where `citekey`'s TL;DR lives -- one JSON file, named the same
    way passages.py's sidecar_path names its own."""
    return config.TLDR_DIR / f"{citekey}.json"


def _fingerprint(con, citekey: str) -> str:
    """sha256 hex of `citekey`'s current parsed text.

    Raises TldrError rather than returning None for "no parsed text
    yet": a summary must be keyed to *some* text, and a caller storing a
    fingerprint of nothing would produce a sidecar that can never be
    told stale from fresh.
    """
    row = con.execute("SELECT parsed_path FROM items WHERE citekey = ?", (citekey,)).fetchone()
    if row is None:
        raise TldrError(
            f"{citekey} is not in the ledger -- run `python -m chitragupta.corpus sync`. "
            "A TL;DR is keyed to a citekey that already exists; it never mints one."
        )
    parsed_path = row[0]
    if not parsed_path or not Path(parsed_path).is_file():
        raise TldrError(
            f"{citekey} has no parsed text yet -- run `python -m chitragupta.corpus "
            "sync` first, then summarise it."
        )
    text = Path(parsed_path).read_text(encoding="utf-8", errors="replace")
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def write(con, citekey: str, summary: str) -> Path:
    """Persist `summary` for `citekey`, keyed to its current parsed-text
    fingerprint. Overwrites whatever was recorded before."""
    summary = summary.strip()
    if not summary:
        raise TldrError("a TL;DR cannot be empty")
    fingerprint = _fingerprint(con, citekey)
    payload = {"citekey": citekey, "summary": summary, "fingerprint": fingerprint}
    path = sidecar_path(citekey)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def _read_sidecar(citekey: str) -> dict | None:
    """The raw payload `write` stored, or None for absent/unreadable --
    the same forgiving read passages.py's `_from_sidecar` gives a
    corrupted file: a missing summary is not an error."""
    try:
        payload = json.loads(sidecar_path(citekey).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError, UnicodeDecodeError):
        return None
    if not isinstance(payload, dict) or not payload.get("summary"):
        return None
    return payload


def read(con, citekey: str) -> dict | None:
    """{"citekey", "summary", "fingerprint", "stale"} for `citekey`, or
    None if no summary has been written yet."""
    payload = _read_sidecar(citekey)
    if payload is None:
        return None
    try:
        current = _fingerprint(con, citekey)
    except TldrError:
        # Uncomputable is stale, not fresh (#509/m-41). `current = None`
        # compared equal to a stored `fingerprint` of `None` -- a sidecar
        # written when the fingerprint could not be computed either --
        # and the pair reported `stale: False`, i.e. "this summary is of
        # the current parse", about a parse this cannot even see. The
        # docstring's promise is the opposite, and a summary nobody can
        # verify is exactly the one a reader should be told to re-check.
        payload["stale"] = True
        return payload
    payload["stale"] = current != payload.get("fingerprint")
    return payload


def _cmd_write(args) -> int:
    summary = sys.stdin.read()
    with ledger.connection() as con:
        path = write(con, args.citekey, summary)
    print(f"wrote {path}")
    return 0


def _cmd_show(args) -> int:
    with ledger.connection() as con:
        result = read(con, args.citekey)
    if result is None:
        print(f"no TL;DR recorded for {args.citekey}")
        return 0
    if args.json:
        print(json.dumps(result, indent=2, sort_keys=True))
        return 0
    note = " [STALE -- re-parsed since this was written]" if result["stale"] else ""
    print(f"{args.citekey}{note}: {result['summary']}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m chitragupta.draft tldr",
        description="A one-paragraph summary per citekey, cached beside a "
        "fingerprint of its parsed text.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_write = sub.add_parser("write", help="Record a summary for one citekey, read from stdin")
    p_write.add_argument("citekey")
    p_write.set_defaults(func=_cmd_write)

    p_show = sub.add_parser("show", help="Print the recorded summary, if any, and its staleness")
    p_show.add_argument("citekey")
    p_show.add_argument("--json", action="store_true", help="Machine-readable output")
    p_show.set_defaults(func=_cmd_show)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except TldrError as exc:
        print(f"[error] {exc}", file=sys.stderr)
        return 1
