"""Does the shipped keyword pipeline still reach the corpus it reached before?

`bench/RESULTS.md`'s 2026-09-03e entry verified the shipped
`extract-keywords` / `seed-topics` stages against the throwaway script
the 2026-09-03c entry used, and got 69.4% / 97.6% / 98.2% coverage on the
2026-09-01 content snapshot. #610 (B14) is what turns that into a number
the paper may quote: it has to hold on the corpus as it is *now*, not on
the snapshot it was measured against.

That entry documented its reproduction as a sequence of CLI calls with
files toggled between them. This is that sequence, committed, so the four
arms are one command instead of a procedure to follow by hand:

| arm | seed list | keyword cap |
| --- | --- | --- |
| topics only | `content/seed_topics.toml` | keywords withheld |
| declared keywords only, uncapped | withheld | `KEYWORD_TOP_N` uncapped |
| topics + keywords, uncapped | both | uncapped |
| topics + keywords, shipped defaults | both | `keyword_top_n` from config |

Coverage is read the way that entry read it -- `(n_docs - len(unmatched))
/ n_docs` from `content/topic_seeds.json`, the stage's own output -- and
never recomputed here, so the number is the pipeline's and not this
script's.

**`content/keywords.toml` is regenerated by the stage in every arm**, not
read from whatever is on disk. Scoring a copied keyword file would
reproduce the old numbers by construction, which is precisely the failure
this benchmark exists to detect.

The arms move `content/seed_topics.toml`, `content/keywords.toml` and
`content/topic_seeds.json`; all three are restored to the shipped
configuration before the script exits, whether it succeeded or not.

Needs the "enrich" Poetry group, a synced corpus and a built
`content/chroma/`.

    CHITRAGUPTA_PROJECT=. .venv-full/bin/python \\
        bench/bench_keyword_pipeline.py --tag 2026-09-04-keyword-pipeline
"""

import argparse
import contextlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from chitragupta import config  # noqa: E402

# Large enough that no corpus reaches it; the entry being reproduced
# calls this arm "uncapped" and used the same trick.
UNCAPPED = 100000
# The 2026-09-03e figures, so a drift is visible in the printed table
# rather than only to a reader who goes and looks them up.
RECORDED = {
    "topics only": 69.4,
    "declared keywords only, uncapped": 97.6,
    "topics + keywords, uncapped": 98.2,
    "topics + keywords, shipped defaults": None,
}


def coverage(seeds: dict) -> float:
    """The stage's own coverage, as a percentage.

    `(n_docs - unmatched) / n_docs`, exactly the arithmetic the
    2026-09-03e entry names -- so a change in what the stage counts as
    matched shows up here, and a change in how this script counts cannot.
    """
    n_docs = seeds["n_docs"]
    if not n_docs:
        return 0.0
    return round(100 * (n_docs - len(seeds["unmatched"])) / n_docs, 1)


def self_check() -> None:
    """Fabricate a coverage this script's arithmetic must read back.

    The failure being guarded is an off-by-one reading of `unmatched`:
    a script that counted matched documents instead would report 30.6%
    where the pipeline means 69.4%, and the comparison against the
    recorded figure would then fail in a way that looked like a corpus
    regression rather than a bench bug.
    """
    assert coverage({"n_docs": 1000, "unmatched": ["x"] * 306}) == 69.4
    assert coverage({"n_docs": 500, "unmatched": []}) == 100.0
    assert coverage({"n_docs": 500, "unmatched": ["x"] * 500}) == 0.0
    assert coverage({"n_docs": 0, "unmatched": []}) == 0.0, "an empty corpus must not divide"


@contextlib.contextmanager
def withheld(*paths: Path):
    """Move files out of the way for one arm and put them back after.

    Moved rather than deleted, and restored in a `finally`: these are
    hand-authored, per-host and gitignored -- `content/seed_topics.toml`
    is the author's own 28-phrase list, and losing it to a crashed
    benchmark would be losing real work.
    """
    stash = Path(tempfile.mkdtemp(prefix="bench-keywords-stash-"))
    moved = []
    for path in paths:
        if path.exists():
            shutil.move(str(path), str(stash / path.name))
            moved.append((stash / path.name, path))
    try:
        yield
    finally:
        for source, destination in moved:
            shutil.move(str(source), str(destination))


def run_stage(stage: str, top_n: "int | None" = None) -> str:
    """One `chitragupta.enrich --stages <stage>` run.

    The stage's own artefact is what gets read afterwards, not its
    stdout: `enrich` has no `--json`, and parsing its human-facing
    report would put a second, driftable reader of the same fact in
    this script.
    """
    env = dict(os.environ)
    if top_n is not None:
        env["KEYWORD_TOP_N"] = str(top_n)
    completed = subprocess.run(
        [sys.executable, "-m", "chitragupta.enrich", "--stages", stage],
        capture_output=True,
        text=True,
        check=False,
        cwd=str(REPO),
        env=env,
    )
    if completed.returncode != 0:
        raise SystemExit(
            f"--stages {stage} exited {completed.returncode}\n"
            f"stdout tail:\n{completed.stdout[-1000:]}\n\nstderr tail:\n{completed.stderr[-1500:]}"
        )
    return completed.stdout


def measure_arm(name: str, top_n: int, keep_seeds: bool, keep_keywords: bool) -> dict:
    """One arm: regenerate keywords at this cap, withhold whichever seed
    source this arm excludes, seed, and read the coverage back."""
    if keep_keywords:
        run_stage("extract-keywords", top_n)
    withhold = []
    if not keep_seeds:
        withhold.append(config.SEED_TOPICS_PATH)
    if not keep_keywords:
        withhold.append(config.KEYWORDS_PATH)
    with withheld(*withhold):
        run_stage("seed-topics")
        seeds = json.loads(config.TOPIC_SEEDS_PATH.read_text(encoding="utf-8"))
    return {
        "arm": name,
        "keyword_top_n": top_n if keep_keywords else None,
        "phrases": len(seeds.get("topics", seeds.get("phrases", {}))) or None,
        "n_docs": seeds["n_docs"],
        "unmatched": len(seeds["unmatched"]),
        "coverage_pct": coverage(seeds),
        "recorded_2026_09_03e": RECORDED[name],
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--tag", required=True, help="names the results directory")
    args = parser.parse_args(argv)
    self_check()

    arms = []
    try:
        arms.append(measure_arm("topics only", UNCAPPED, True, False))
        arms.append(measure_arm("declared keywords only, uncapped", UNCAPPED, False, True))
        arms.append(measure_arm("topics + keywords, uncapped", UNCAPPED, True, True))
        arms.append(
            measure_arm("topics + keywords, shipped defaults", config.KEYWORD_TOP_N, True, True)
        )
    finally:
        # Leave the corpus in the shipped configuration whatever
        # happened above: the last arm above already is the shipped one,
        # but an arm that raised partway would not have restored it.
        run_stage("extract-keywords")
        run_stage("seed-topics")

    print(f"\n{'arm':40} {'phrases':>8} {'coverage':>9} {'recorded':>9} {'delta_pp':>9}")
    for arm in arms:
        recorded = arm["recorded_2026_09_03e"]
        delta = "-" if recorded is None else round(arm["coverage_pct"] - recorded, 1)
        print(
            f"{arm['arm']:40} {str(arm['phrases']):>8} {arm['coverage_pct']:>8}% "
            f"{str(recorded):>9} {str(delta):>9}"
        )

    out_dir = REPO / "bench" / "results" / args.tag
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "keyword_pipeline.json").write_text(
        json.dumps({"arms": arms, "shipped_keyword_top_n": config.KEYWORD_TOP_N}, indent=2),
        "utf-8",
    )
    print(f"\nwrote {out_dir / 'keyword_pipeline.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
