"""Re-render the diagram exports and record which source each came from (#850).

    python scripts/render_diagrams.py                 # every diagram
    python scripts/render_diagrams.py v1-overview     # just these
    python scripts/render_diagrams.py --puppeteer-config pp.json
    python scripts/render_diagrams.py --sync          # stamp the theme, copy to .mmd

Runs the command docs/DIAGRAMS.md documents,
`mmdc -i <name>.mmd -o svg/<name>.svg -b white -w 1900`, for each
`docs/diagrams/<name>.mmd`, then records the source's fingerprint in
`docs/diagrams/svg/sources.json`. `tests/test_diagrams_in_sync.py` checks
every export against that manifest, so an `.mmd` edited without a
re-render fails with a message naming the source to re-render -- where
before only a stale *aid name* in an SVG was caught, and any other edit
to a diagram left its picture silently out of date.

The manifest records what was rendered, not what was intended: a render
that fails records nothing, so the file can never claim a freshness no
render produced.

mermaid-cli 11 is the pinned major: 12 dropped the `-w` flag this command
uses. A host that cannot sandbox Chromium (a container, CI) passes
`--puppeteer-config` a JSON file holding `{"args": ["--no-sandbox"]}`.

**The house theme (#1017).** Every diagram opens with one Mermaid init
directive, and every flowchart closes with the same four role
`classDef`s: `flow`, `alt`, `key` and `absent`, the roles
docs/TIKZ-STYLE.md gives the TikZ palette. Both are generated here, from
that file's `\\definecolor` block, so no hex is typed twice and the two
halves of the house style cannot drift. GitHub renders a fenced block as
it stands and cannot include a shared file, so the text has to be in all
thirteen blocks; `--sync` is what puts it there. It rewrites each fenced
block in docs/DIAGRAMS.md to carry the current theme and copies the block
into its `.mmd`, which is also the copy step that file used to ask for
by hand. It renders nothing: run the script again, without `--sync`, on
the names it prints.
"""

import argparse
import hashlib
import json
import re
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DIAGRAMS = REPO_ROOT / "docs" / "diagrams"
MANIFEST = DIAGRAMS / "svg" / "sources.json"
DIAGRAMS_MD = REPO_ROOT / "docs" / "DIAGRAMS.md"
STYLE_DOC = REPO_ROOT / "docs" / "TIKZ-STYLE.md"

EDITING_HEADING = "## ✏ Editing these"
_NAME_ROW = re.compile(r"^\| [^|]+ \| `([\w-]+)` \|$", re.MULTILINE)
_BLOCK = re.compile(r"(```mermaid\n)(.*?)(```)", re.DOTALL)
_TITLE = re.compile(r"\A---\ntitle:.*?\n---\n", re.DOTALL)

_PALETTE_HEADING = "## 🎨 The house palette"
_DEFINECOLOR = re.compile(r"\\definecolor\{(cg\w+)\}\{HTML\}\{([0-9A-Fa-f]{6})\}")

ROLES = ("flow", "alt", "key", "absent")
# TikZ's `<colour>!<n>`: the fill tint docs/TIKZ-STYLE.md recommends,
# inside its 8-15 band, and the grey an absent node is drawn in.
_FILL_TINT = 10
_MUTE_TINT = 50
# The diagram types Mermaid lets a `classDef` style. A sequence diagram
# has none, so the directive alone gives it the palette.
_TAKES_CLASSDEF = ("flowchart", "graph", "stateDiagram", "stateDiagram-v2")
_INIT = re.compile(r"\A%%\{init:.*?\}%%\n", re.DOTALL)
_ROLES_MARK = "%% house roles: generated by scripts/render_diagrams.py --sync"
_ROLE_LINE = re.compile(
    rf"^[ \t]*(?:{re.escape(_ROLES_MARK)}|classDef (?:{'|'.join(ROLES)}) .*)\n", re.MULTILINE
)


def fingerprint(source: Path) -> str:
    """sha256 of `source` with line endings normalised to LF, so a CRLF
    checkout (Windows under `core.autocrlf`) matches the manifest too."""
    return hashlib.sha256(source.read_bytes().replace(b"\r\n", b"\n")).hexdigest()


def export_names(text: str) -> list[str]:
    """The `<name>` column of DIAGRAMS.md's "Editing these" table, in
    order. That table is the one hand-kept list of diagrams (#866), and
    its order is what ties fenced block i to export i. Refuses to return
    an empty list: an empty list would make every check over it vanish
    while the run stayed green."""
    _, found, tail = text.partition(EDITING_HEADING)
    names = _NAME_ROW.findall(tail) if found else []
    if not names:
        raise ValueError(
            f"docs/DIAGRAMS.md no longer has a {EDITING_HEADING!r} table to read. "
            "Rewording it is fine; teach _NAME_ROW the new shape in the same change."
        )
    return names


def blocks(text: str) -> list[str]:
    """Every fenced `mermaid` block's body, in document order."""
    return [match.group(2) for match in _BLOCK.finditer(text)]


def palette(text: str) -> dict[str, str]:
    """`cgName -> RRGGBB` from docs/TIKZ-STYLE.md's house-palette section:
    the one place a hex in the house style is written."""
    _, _, tail = text.partition(_PALETTE_HEADING)
    colours = {name: value.upper() for name, value in _DEFINECOLOR.findall(tail.split("\n## ")[0])}
    if not colours:
        raise ValueError(
            f"docs/TIKZ-STYLE.md has no \\definecolor block under {_PALETTE_HEADING!r}"
        )
    return colours


def tint(colour: str, percent: int) -> str:
    """TikZ's `colour!percent`: that much of `colour`, the rest white."""
    channels = (int(colour[i : i + 2], 16) for i in (0, 2, 4))
    return "".join(
        f"{round(c * percent / 100 + 255 * (100 - percent) / 100):02X}" for c in channels
    )


def house_theme(colours: dict[str, str]) -> tuple[str, str]:
    """The init directive every diagram opens with, and the role
    `classDef`s every flowchart closes with, both built from `colours`.

    The roles are docs/TIKZ-STYLE.md's: `flow` the spine, `alt` a second
    class of node, `key` the one thing the figure is about, `absent`
    what is off the path. The theme variables make an unclassed node
    look like `flow`, and give sequence and state diagrams, which take
    no `classDef`, the same palette."""
    ink, flow, alt, key = (colours[n] for n in ("cgInk", "cgFlow", "cgAlt", "cgAccent"))
    mute = tint(ink, _MUTE_TINT)
    # No fontFamily: Mermaid sizes each label box with its own font stack,
    # and a system-ui stack it does not measure with leaves the last
    # character of a label clipped outside the box.
    variables = {
        "fontSize": "14px",
        "primaryColor": f"#{tint(flow, _FILL_TINT)}",
        "primaryBorderColor": f"#{flow}",
        "primaryTextColor": f"#{ink}",
        "lineColor": f"#{flow}",
        "secondaryColor": f"#{tint(alt, _FILL_TINT)}",
        "secondaryBorderColor": f"#{alt}",
        "tertiaryColor": f"#{tint(key, _FILL_TINT)}",
        "tertiaryBorderColor": f"#{key}",
    }
    init = (
        "%%{init: " + json.dumps({"theme": "base", "themeVariables": variables}, indent=2) + "}%%"
    )

    def role(name: str, fill: str, stroke: str, width: str, dash: str = "") -> str:
        return (
            f"classDef {name} fill:#{fill},stroke:#{stroke},stroke-width:{width},{dash}color:#{ink}"
        )

    roles = [
        _ROLES_MARK,
        role("flow", tint(flow, _FILL_TINT), flow, "1.4px"),
        role("alt", tint(alt, _FILL_TINT), alt, "1.4px"),
        role("key", tint(key, _FILL_TINT), key, "2px"),
        role("absent", "FFFFFF", mute, "1.2px", "stroke-dasharray:4 3,"),
    ]
    return init, "\n".join(f"  {line}" for line in roles)


def _diagram_type(body: str) -> str:
    """The diagram keyword: the first word of the first line that is not
    a `%%` comment."""
    for line in body.splitlines():
        if line.strip() and not line.lstrip().startswith("%%"):
            return line.split()[0]
    return ""


def stamp(block: str, theme: tuple[str, str]) -> str:
    """`block` carrying exactly `theme`: any earlier directive and role
    definitions are dropped first, so restamping after a palette change
    replaces them rather than stacking a second copy."""
    init, roles = theme
    body = _ROLE_LINE.sub("", _INIT.sub("", block)).rstrip()
    if _diagram_type(body) in _TAKES_CLASSDEF:
        body += "\n\n" + roles
    return f"{init}\n{body}\n"


def sync() -> list[str]:
    """Stamp the current theme into every fenced block of docs/DIAGRAMS.md
    and copy each block into its `.mmd`, keeping the `.mmd`'s title
    front matter. Returns the names whose `.mmd` changed: the ones that
    need re-rendering."""
    text = DIAGRAMS_MD.read_text(encoding="utf-8")
    names = export_names(text)
    found = blocks(text)
    if len(found) != len(names):
        raise ValueError(
            f"docs/DIAGRAMS.md has {len(found)} fenced blocks but its 'Editing these' "
            f"table lists {len(names)}. Add or remove the row with the diagram."
        )
    theme = house_theme(palette(STYLE_DOC.read_text(encoding="utf-8")))
    stamped = iter([stamp(block, theme) for block in found])
    text = _BLOCK.sub(lambda m: m.group(1) + next(stamped) + m.group(3), text)
    DIAGRAMS_MD.write_text(text, encoding="utf-8")
    changed = []
    for name, block in zip(names, blocks(text)):
        mmd = DIAGRAMS / f"{name}.mmd"
        old = mmd.read_text(encoding="utf-8") if mmd.is_file() else ""
        title = _TITLE.match(old)
        new = (title.group(0) if title else "") + block
        if new != old:
            mmd.write_text(new, encoding="utf-8")
            changed.append(name)
    return changed


def _argv(name: str, puppeteer_config: "str | None") -> list[str]:
    argv = [
        "mmdc",
        "-i",
        str(DIAGRAMS / f"{name}.mmd"),
        "-o",
        str(DIAGRAMS / "svg" / f"{name}.svg"),
        "-b",
        "white",
        "-w",
        "1900",
    ]
    return argv + ["-p", puppeteer_config] if puppeteer_config else argv


def render(
    names: list[str],
    *,
    run: Callable[..., subprocess.CompletedProcess] = subprocess.run,
    puppeteer_config: "str | None" = None,
) -> int:
    """Render each of `names` and record the ones that rendered. Returns
    0 when all did, 1 when any failed -- after recording the others, so a
    second run only has the failures left to do."""
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8")) if MANIFEST.is_file() else {}
    failed = 0
    for name in names:
        try:
            result = run(_argv(name, puppeteer_config), capture_output=True, text=True, check=False)
        except FileNotFoundError:
            print(
                "mmdc is not on PATH: npm install -g @mermaid-js/mermaid-cli@11",
                file=sys.stderr,
            )
            return 1
        if result.returncode != 0:
            print(f"{name}: mmdc exited {result.returncode}\n{result.stderr}", file=sys.stderr)
            failed = 1
            continue
        manifest[name] = fingerprint(DIAGRAMS / f"{name}.mmd")
        print(f"rendered {name}")
    if manifest:
        MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return failed


def main(argv: "list[str] | None" = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("names", nargs="*", help="diagram names; every .mmd when omitted")
    parser.add_argument("--puppeteer-config", help="passed to mmdc as -p")
    parser.add_argument(
        "--sync",
        action="store_true",
        help="stamp the house theme into docs/DIAGRAMS.md's blocks and copy them to the .mmd files",
    )
    args = parser.parse_args(argv)
    if args.sync:
        changed = sync()
        if changed:
            print(f"re-render: python scripts/render_diagrams.py {' '.join(changed)}")
        else:
            print("every .mmd already matches its block")
        return 0
    known = sorted(path.stem for path in DIAGRAMS.glob("*.mmd"))
    unknown = sorted(set(args.names) - set(known))
    if unknown:
        print(f"no such diagram: {', '.join(unknown)} (have: {', '.join(known)})", file=sys.stderr)
        return 2
    return render(args.names or known, puppeteer_config=args.puppeteer_config)


if __name__ == "__main__":
    sys.exit(main())
